# plotpy setup configuration file

[build-system]
requires = ["setuptools", "wheel", "cython ~= 0.29.0", "numpy >= 1.3"]
build-backend = "setuptools.build_meta"

[project]
name = "plotpy"
authors = [{ name = "Codra", email = "p.raybaut@codra.fr" }]
description = "Curve and image plotting tools for Python/Qt applications"
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Human Machine Interfaces",
    "Topic :: Software Development :: User Interfaces",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: OS Independent",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
requires-python = ">=3.8, <4"
dependencies = [
    "guidata>=3.0.1",
    "PythonQwt>=0.10",
    "NumPy>=1.3",
    "SciPy>=0.7",
    "Pillow",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/CODRA-Ingenierie-Informatique/plotpy/"
Documentation = "https://plotpy.readthedocs.io/en/latest/"

[project.scripts]

[project.optional-dependencies]
dev = ["black", "isort", "pylint", "Coverage"]
doc = [
    "PyQt5",
    "sphinx",
    "sphinx-copybutton",
    "sphinx_qt_documentation",
    "python-docs-theme",
]
test = ["pytest", "pytest-cov", "pytest-qt", "pytest-xvfb"]

[tool.setuptools.packages.find]
include = ["plotpy*"]

[tool.setuptools.package-data]
"*" = ["*.png", "*.svg", "*.mo", "*.chm", "*.cfg", "*.toml", ".dcm", ".ui"]

[tool.setuptools.dynamic]
version = { attr = "plotpy.__version__" }
